// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFile() {
  return window['go']['main']['App']['BrowseFile']();
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CreateBranch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateIssue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateOrUpdateFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateOrUpdateFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateRelease(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateRelease'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRepo'](arg1, arg2, arg3, arg4);
}

export function DeleteAllFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteAllFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteAsset(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DeleteAsset'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteBranch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2, arg3, arg4);
}

export function DeleteRelease(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRelease'](arg1, arg2, arg3, arg4);
}

export function DeleteRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRepo'](arg1, arg2, arg3);
}

export function DeleteRepoFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteRepoFile'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function EditRelease(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['EditRelease'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GetBranches(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBranches'](arg1, arg2, arg3);
}

export function GetCommits(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCommits'](arg1, arg2, arg3, arg4);
}

export function GetFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFileContent'](arg1, arg2, arg3, arg4);
}

export function GetIssueComments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetIssueComments'](arg1, arg2, arg3, arg4);
}

export function GetIssues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetIssues'](arg1, arg2, arg3, arg4);
}

export function GetPullRequests(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPullRequests'](arg1, arg2, arg3, arg4);
}

export function GetReleases(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReleases'](arg1, arg2, arg3);
}

export function GetRepoDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRepoDetail'](arg1, arg2, arg3);
}

export function GetRepoFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRepoFiles'](arg1, arg2, arg3, arg4);
}

export function GetRepos(arg1) {
  return window['go']['main']['App']['GetRepos'](arg1);
}

export function GetUserInfo(arg1) {
  return window['go']['main']['App']['GetUserInfo'](arg1);
}

export function LoadTokens() {
  return window['go']['main']['App']['LoadTokens']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveTokens(arg1, arg2) {
  return window['go']['main']['App']['SaveTokens'](arg1, arg2);
}

export function SearchRepos(arg1, arg2) {
  return window['go']['main']['App']['SearchRepos'](arg1, arg2);
}

export function UpdateRepo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateRepo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadAsset(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadAsset'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadFolder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadFolder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadLocalFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadLocalFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}
