// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseFile():Promise<string>;

export function BrowseFolder():Promise<string>;

export function CreateBranch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateOrUpdateFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function CreateRelease(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean):Promise<string>;

export function CreateRepo(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function DeleteAllFiles(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DeleteAsset(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<string>;

export function DeleteBranch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DeleteRelease(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function DeleteRepo(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DeleteRepoFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function DownloadFile(arg1:string,arg2:string):Promise<boolean>;

export function EditRelease(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<string>;

export function GetBranches(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetCommits(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetFileContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetIssueComments(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetIssues(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetPullRequests(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetReleases(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRepoDetail(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRepoFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetRepos(arg1:string):Promise<string>;

export function GetUserInfo(arg1:string):Promise<string>;

export function LoadTokens():Promise<main.Tokens>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveTokens(arg1:string,arg2:string):Promise<boolean>;

export function SearchRepos(arg1:string,arg2:string):Promise<string>;

export function UpdateRepo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function UploadAsset(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<string>;

export function UploadFolder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UploadLocalFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;
